author:
  displayName: The Post IO
  biography: I'm a publishing platform where authors keep their data 
  picture: https://thepost.io/images/mosaic_zoom.png
  website: https://thepost.io
  twitter: jonathanlurie
  github: thepostio

# This section is not mandatory but it will show a list of articles in the profile page.
# Otherwise not article will be listed, though they will still be accessible through URL
articles:
  - getting-started
  - no-cover
  - markdown-demo
  - some-code
